{ deviceId: [Getter/Setter],
  generationId: [Getter],
  etag: [Getter],
  connectionState: [Getter],
  status: [Getter/Setter],
  statusReason: [Getter/Setter],
  connectionStateUpdatedTime: [Getter],
  statusUpdatedTime: [Getter],
  lastActivityTime: [Getter],
  cloudToDeviceMessageCount: [Getter],
  authentication: [Getter] }
{ _readableState:
   { objectMode: false,
     highWaterMark: 16384,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: true,
     ended: true,
     endEmitted: true,
     reading: false,
     sync: true,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null,
     resumeScheduled: false },
  readable: false,
  domain: null,
  _events:
   { end: [ [Function: responseOnEnd], [Function: onResponseEnd] ],
     error: [Function],
     data: [Function: onResponseData] },
  _maxListeners: undefined,
  socket:
   { _connecting: false,
     _hadError: false,
     _handle: null,
     _parent: null,
     _host: 'demo-hub.azure-devices.net',
     _readableState:
      { objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: false,
     domain: null,
     _events:
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        error: [Object],
        free: [Function: onFree],
        close: [Object],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        secure: [Function] },
     _maxListeners: undefined,
     _writableState:
      { objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false },
     writable: false,
     allowHalfOpen: false,
     destroyed: true,
     bytesRead: 884,
     _bytesDispatched: 729,
     _pendingData: null,
     _pendingEncoding: '',
     _tlsOptions:
      { secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: undefined,
        NPNProtocols: undefined,
        requestOCSP: undefined },
     _secureEstablished: true,
     _securePending: false,
     _newSessionPending: false,
     _controlReleased: true,
     _SNICallback: null,
     ssl:
      { onhandshakestart: [Function],
        onhandshakedone: [Function],
        onocspresponse: [Function],
        onerror: [Function] },
     servername: null,
     npnProtocol: undefined,
     authorized: true,
     authorizationError: null,
     encrypted: true,
     parser: null,
     _httpMessage:
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        writable: true,
        _last: true,
        chunkedEncoding: true,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: {},
        _hasBody: true,
        _trailer: '',
        finished: true,
        _hangupClose: false,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'PUT /devices/mySecondDevice?api-version=2016-02-03 HTTP/1.1\r\nAuthorization: SharedAccessSignature sr=demo-hub.azure-devices.net&sig=7spdFZr8IOCh64n2W5E1Aav4xrVwjc2qfg%2B6bhpeEZ4%3D&skn=iothubowner&se=1463986394\r\niothub-name: demo-hub\r\nContent-Type: application/json; charset=utf-8\r\nUser-Agent: azure-iothub/1.0.8\r\nHost: demo-hub.azure-devices.net\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        agent: [Object],
        socketPath: undefined,
        method: 'PUT',
        path: '/devices/mySecondDevice?api-version=2016-02-03',
        parser: null,
        res: [Circular] },
     read: [Function],
     _consuming: true,
     server: null,
     _requestCert: true,
     _rejectUnauthorized: true,
     _idleNext: null,
     _idlePrev: null,
     _idleTimeout: -1 },
  connection:
   { _connecting: false,
     _hadError: false,
     _handle: null,
     _parent: null,
     _host: 'demo-hub.azure-devices.net',
     _readableState:
      { objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: false,
     domain: null,
     _events:
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        error: [Object],
        free: [Function: onFree],
        close: [Object],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        secure: [Function] },
     _maxListeners: undefined,
     _writableState:
      { objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false },
     writable: false,
     allowHalfOpen: false,
     destroyed: true,
     bytesRead: 884,
     _bytesDispatched: 729,
     _pendingData: null,
     _pendingEncoding: '',
     _tlsOptions:
      { secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: undefined,
        NPNProtocols: undefined,
        requestOCSP: undefined },
     _secureEstablished: true,
     _securePending: false,
     _newSessionPending: false,
     _controlReleased: true,
     _SNICallback: null,
     ssl:
      { onhandshakestart: [Function],
        onhandshakedone: [Function],
        onocspresponse: [Function],
        onerror: [Function] },
     servername: null,
     npnProtocol: undefined,
     authorized: true,
     authorizationError: null,
     encrypted: true,
     parser: null,
     _httpMessage:
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        writable: true,
        _last: true,
        chunkedEncoding: true,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: {},
        _hasBody: true,
        _trailer: '',
        finished: true,
        _hangupClose: false,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'PUT /devices/mySecondDevice?api-version=2016-02-03 HTTP/1.1\r\nAuthorization: SharedAccessSignature sr=demo-hub.azure-devices.net&sig=7spdFZr8IOCh64n2W5E1Aav4xrVwjc2qfg%2B6bhpeEZ4%3D&skn=iothubowner&se=1463986394\r\niothub-name: demo-hub\r\nContent-Type: application/json; charset=utf-8\r\nUser-Agent: azure-iothub/1.0.8\r\nHost: demo-hub.azure-devices.net\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        agent: [Object],
        socketPath: undefined,
        method: 'PUT',
        path: '/devices/mySecondDevice?api-version=2016-02-03',
        parser: null,
        res: [Circular] },
     read: [Function],
     _consuming: true,
     server: null,
     _requestCert: true,
     _rejectUnauthorized: true,
     _idleNext: null,
     _idlePrev: null,
     _idleTimeout: -1 },
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  httpVersion: '1.1',
  complete: true,
  headers:
   { 'content-length': '696',
     'content-type': 'application/json; charset=utf-8',
     etag: '"MA=="',
     server: 'Microsoft-HTTPAPI/2.0',
     date: 'Mon, 23 May 2016 05:53:16 GMT',
     connection: 'close' },
  rawHeaders:
   [ 'Content-Length',
     '696',
     'Content-Type',
     'application/json; charset=utf-8',
     'ETag',
     '"MA=="',
     'Server',
     'Microsoft-HTTPAPI/2.0',
     'Date',
     'Mon, 23 May 2016 05:53:16 GMT',
     'Connection',
     'close' ],
  trailers: {},
  rawTrailers: [],
  _pendings: [],
  _pendingIndex: 0,
  upgrade: false,
  url: '',
  method: null,
  statusCode: 200,
  statusMessage: 'OK',
  client:
   { _connecting: false,
     _hadError: false,
     _handle: null,
     _parent: null,
     _host: 'demo-hub.azure-devices.net',
     _readableState:
      { objectMode: false,
        highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: false,
     domain: null,
     _events:
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        error: [Object],
        free: [Function: onFree],
        close: [Object],
        agentRemove: [Function: onRemove],
        drain: [Function: ondrain],
        secure: [Function] },
     _maxListeners: undefined,
     _writableState:
      { objectMode: false,
        highWaterMark: 16384,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false },
     writable: false,
     allowHalfOpen: false,
     destroyed: true,
     bytesRead: 884,
     _bytesDispatched: 729,
     _pendingData: null,
     _pendingEncoding: '',
     _tlsOptions:
      { secureContext: [Object],
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: undefined,
        NPNProtocols: undefined,
        requestOCSP: undefined },
     _secureEstablished: true,
     _securePending: false,
     _newSessionPending: false,
     _controlReleased: true,
     _SNICallback: null,
     ssl:
      { onhandshakestart: [Function],
        onhandshakedone: [Function],
        onocspresponse: [Function],
        onerror: [Function] },
     servername: null,
     npnProtocol: undefined,
     authorized: true,
     authorizationError: null,
     encrypted: true,
     parser: null,
     _httpMessage:
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        writable: true,
        _last: true,
        chunkedEncoding: true,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedHeader: {},
        _hasBody: true,
        _trailer: '',
        finished: true,
        _hangupClose: false,
        _headerSent: true,
        socket: [Circular],
        connection: [Circular],
        _header: 'PUT /devices/mySecondDevice?api-version=2016-02-03 HTTP/1.1\r\nAuthorization: SharedAccessSignature sr=demo-hub.azure-devices.net&sig=7spdFZr8IOCh64n2W5E1Aav4xrVwjc2qfg%2B6bhpeEZ4%3D&skn=iothubowner&se=1463986394\r\niothub-name: demo-hub\r\nContent-Type: application/json; charset=utf-8\r\nUser-Agent: azure-iothub/1.0.8\r\nHost: demo-hub.azure-devices.net\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        agent: [Object],
        socketPath: undefined,
        method: 'PUT',
        path: '/devices/mySecondDevice?api-version=2016-02-03',
        parser: null,
        res: [Circular] },
     read: [Function],
     _consuming: true,
     server: null,
     _requestCert: true,
     _rejectUnauthorized: true,
     _idleNext: null,
     _idlePrev: null,
     _idleTimeout: -1 },
  _consuming: true,
  _dumped: false,
  req:
   { domain: null,
     _events: { error: [Function] },
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     writable: true,
     _last: true,
     chunkedEncoding: true,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedHeader: {},
     _hasBody: true,
     _trailer: '',
     finished: true,
     _hangupClose: false,
     _headerSent: true,
     socket:
      { _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'demo-hub.azure-devices.net',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 884,
        _bytesDispatched: 729,
        _pendingData: null,
        _pendingEncoding: '',
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        ssl: [Object],
        servername: null,
        npnProtocol: undefined,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        server: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     connection:
      { _connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'demo-hub.azure-devices.net',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        destroyed: true,
        bytesRead: 884,
        _bytesDispatched: 729,
        _pendingData: null,
        _pendingEncoding: '',
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        ssl: [Object],
        servername: null,
        npnProtocol: undefined,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        server: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1 },
     _header: 'PUT /devices/mySecondDevice?api-version=2016-02-03 HTTP/1.1\r\nAuthorization: SharedAccessSignature sr=demo-hub.azure-devices.net&sig=7spdFZr8IOCh64n2W5E1Aav4xrVwjc2qfg%2B6bhpeEZ4%3D&skn=iothubowner&se=1463986394\r\niothub-name: demo-hub\r\nContent-Type: application/json; charset=utf-8\r\nUser-Agent: azure-iothub/1.0.8\r\nHost: demo-hub.azure-devices.net\r\nConnection: close\r\nTransfer-Encoding: chunked\r\n\r\n',
     _headers:
      { authorization: 'SharedAccessSignature sr=demo-hub.azure-devices.net&sig=7spdFZr8IOCh64n2W5E1Aav4xrVwjc2qfg%2B6bhpeEZ4%3D&skn=iothubowner&se=1463986394',
        'iothub-name': 'demo-hub',
        'content-type': 'application/json; charset=utf-8',
        'user-agent': 'azure-iothub/1.0.8',
        host: 'demo-hub.azure-devices.net' },
     _headerNames:
      { authorization: 'Authorization',
        'iothub-name': 'iothub-name',
        'content-type': 'Content-Type',
        'user-agent': 'User-Agent',
        host: 'Host' },
     agent:
      { domain: null,
        _events: [Object],
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     method: 'PUT',
     path: '/devices/mySecondDevice?api-version=2016-02-03',
     parser: null,
     res: [Circular] },
  read: [Function] }
Device id: mySecondDevice
Device key: jjDgk+GfsJe0mdu7061mVP3inVUO1HRTk3oh+s8xefc=
Device Info: [object Object]